\set ON_ERROR_STOP on

ALTER ROLE chat_identity NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_auth NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_key_directory NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_key_transparency NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_mailbox NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_object NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_group NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_backup NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_config NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE chat_diagnostic NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

REVOKE CONNECT, TEMPORARY ON DATABASE chat_identity FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_auth FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_key_directory FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_key_transparency FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_mailbox FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_object FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_group FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_backup FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_config FROM PUBLIC;
REVOKE CONNECT, TEMPORARY ON DATABASE chat_diagnostic FROM PUBLIC;

GRANT CONNECT, TEMPORARY ON DATABASE chat_identity TO chat_identity;
GRANT CONNECT, TEMPORARY ON DATABASE chat_auth TO chat_auth;
GRANT CONNECT, TEMPORARY ON DATABASE chat_key_directory TO chat_key_directory;
GRANT CONNECT, TEMPORARY ON DATABASE chat_key_transparency TO chat_key_transparency;
GRANT CONNECT, TEMPORARY ON DATABASE chat_mailbox TO chat_mailbox;
GRANT CONNECT, TEMPORARY ON DATABASE chat_object TO chat_object;
GRANT CONNECT, TEMPORARY ON DATABASE chat_group TO chat_group;
GRANT CONNECT, TEMPORARY ON DATABASE chat_backup TO chat_backup;
GRANT CONNECT, TEMPORARY ON DATABASE chat_config TO chat_config;
GRANT CONNECT, TEMPORARY ON DATABASE chat_diagnostic TO chat_diagnostic;
