export type Locale = "zh-CN" | "en";
export type ThemeMode = "dark" | "light";

const LOCALE_STORAGE_KEY = "chat.preferences.locale.v1";
const THEME_STORAGE_KEY = "chat.preferences.theme.v1";

export const translations = {
  "zh-CN": {
    appName: "安全聊天",
    localDevelopment: "本地开发环境",
    welcomeBack: "欢迎回来",
    loginIntro: "输入名字和密码登录。",
    registerIntro: "创建账号后，系统会自动生成可用于添加好友的聊天号。",
    login: "登录",
    register: "注册",
    name: "名字",
    nameHint: "3–32 个字符，仅支持英文字母、数字和下划线。",
    password: "密码",
    passwordHint: "至少 8 个字符。",
    confirmPassword: "再次输入密码",
    passwordsMismatch: "两次输入的密码不一致。",
    pleaseWait: "请稍候…",
    createAccount: "创建账号",
    noAccount: "还没有账号？",
    clickRegister: "点击注册",
    haveAccount: "已经有账号？",
    backToLogin: "返回登录",
    restoringSession: "正在恢复会话…",
    logout: "退出登录",
    settings: "设置",
    closeSettings: "关闭设置",
    language: "语言",
    appearance: "外观",
    chinese: "中文",
    english: "English",
    darkMode: "深色模式",
    darkModeDescription: "黑灰色界面",
    lightMode: "亮色模式",
    lightModeDescription: "白色界面",
    chats: "聊天",
    contacts: "联系人",
    requests: "好友申请",
    addFriend: "添加好友",
    searchById: "输入聊天号或账号 UUID",
    exactSearchOnly: "只支持聊天号或 UUID 精确搜索，不支持按名字查找。",
    search: "搜索",
    noSearchResult: "没有找到该账号。",
    sendRequest: "发送申请",
    requestMessage: "申请留言",
    defaultRequest: "Hi，我是{0}",
    requestSent: "好友申请已发送。",
    incomingRequests: "收到的申请",
    outgoingRequests: "发出的申请",
    noRequests: "暂无好友申请。",
    accept: "通过",
    reject: "拒绝",
    pending: "等待对方处理",
    accepted: "已通过",
    rejected: "已拒绝",
    startChat: "聊天",
    noContacts: "还没有联系人，请先通过聊天号添加好友。",
    createGroup: "创建群聊",
    groupName: "群聊名称",
    chooseContacts: "选择联系人",
    create: "创建",
    cancel: "取消",
    conversations: "会话",
    noConversations: "添加联系人或创建群聊后，会话会显示在这里。",
    unknownUser: "未知用户",
    noMessagesYet: "暂无消息",
    conversation: "会话",
    plaintextDev: "明文开发版 V0",
    emptyMessagesTitle: "还没有消息",
    emptyMessagesBody: "发送第一条消息。",
    writeMessage: "输入消息",
    send: "发送",
    landingBody: "从左侧选择联系人、好友申请或群聊。",
    realtimeConnected: "实时连接已建立",
    realtimeConnecting: "实时连接中",
    realtimeOffline: "实时连接已断开",
    rustCore: "Rust 核心",
    chatId: "聊天号",
    accountUuid: "账号 UUID",
    copy: "复制",
    copied: "已复制",
    group: "群聊",
    groupCode: "群号",
    members: "成员",
    groupSettings: "群聊管理",
    roleOwner: "群主",
    roleAdmin: "管理员",
    roleMember: "成员",
    addMember: "添加成员",
    remove: "移除",
    setAdmin: "设为管理员",
    removeAdmin: "取消管理员",
    dissolveGroup: "解散群聊",
    dissolveConfirm: "确定解散该群聊吗？此操作不可撤销。",
    memberCanAdd: "所有群成员都可以邀请自己的联系人入群。",
    ownerPermissions: "群主可解散群聊、增删成员并设置管理员。",
    adminPermissions: "管理员可添加和移除普通成员。",
    memberPermissions: "普通成员只能添加自己的联系人。",
    close: "关闭",
    refresh: "刷新",
  },
  en: {
    appName: "Secure Chat",
    localDevelopment: "Local Development",
    welcomeBack: "Welcome back",
    loginIntro: "Enter your name and password to log in.",
    registerIntro:
      "After registration, the app generates a public Chat ID that others can use to add you.",
    login: "Log in",
    register: "Register",
    name: "Name",
    nameHint: "3–32 letters, numbers, or underscores.",
    password: "Password",
    passwordHint: "At least 8 characters.",
    confirmPassword: "Confirm password",
    passwordsMismatch: "Passwords do not match.",
    pleaseWait: "Please wait…",
    createAccount: "Create account",
    noAccount: "No account yet?",
    clickRegister: "Register",
    haveAccount: "Already have an account?",
    backToLogin: "Back to login",
    restoringSession: "Restoring your session…",
    logout: "Log out",
    settings: "Settings",
    closeSettings: "Close settings",
    language: "Language",
    appearance: "Appearance",
    chinese: "中文",
    english: "English",
    darkMode: "Dark mode",
    darkModeDescription: "Black and gray interface",
    lightMode: "Light mode",
    lightModeDescription: "White interface",
    chats: "Chats",
    contacts: "Contacts",
    requests: "Friend requests",
    addFriend: "Add friend",
    searchById: "Enter Chat ID or account UUID",
    exactSearchOnly:
      "Exact Chat ID or UUID search only. Display-name search is disabled.",
    search: "Search",
    noSearchResult: "No account was found.",
    sendRequest: "Send request",
    requestMessage: "Request message",
    defaultRequest: "Hi, I'm {0}",
    requestSent: "Friend request sent.",
    incomingRequests: "Incoming",
    outgoingRequests: "Outgoing",
    noRequests: "No friend requests.",
    accept: "Accept",
    reject: "Reject",
    pending: "Waiting for response",
    accepted: "Accepted",
    rejected: "Rejected",
    startChat: "Chat",
    noContacts: "You have no contacts yet. Add someone using their Chat ID.",
    createGroup: "Create group",
    groupName: "Group name",
    chooseContacts: "Choose contacts",
    create: "Create",
    cancel: "Cancel",
    conversations: "Conversations",
    noConversations: "Contacts and groups will appear here.",
    unknownUser: "Unknown user",
    noMessagesYet: "No messages yet",
    conversation: "Conversation",
    plaintextDev: "PLAINTEXT DEV V0",
    emptyMessagesTitle: "No messages yet",
    emptyMessagesBody: "Send the first message.",
    writeMessage: "Write a message",
    send: "Send",
    landingBody: "Choose chats, contacts, friend requests, or groups on the left.",
    realtimeConnected: "Realtime connected",
    realtimeConnecting: "Realtime connecting",
    realtimeOffline: "Realtime offline",
    rustCore: "Rust core",
    chatId: "Chat ID",
    accountUuid: "Account UUID",
    copy: "Copy",
    copied: "Copied",
    group: "Group",
    groupCode: "Group ID",
    members: "Members",
    groupSettings: "Group management",
    roleOwner: "Owner",
    roleAdmin: "Admin",
    roleMember: "Member",
    addMember: "Add member",
    remove: "Remove",
    setAdmin: "Make admin",
    removeAdmin: "Remove admin",
    dissolveGroup: "Dissolve group",
    dissolveConfirm: "Dissolve this group? This cannot be undone.",
    memberCanAdd: "Every group member can invite their own contacts.",
    ownerPermissions:
      "The owner can dissolve the group, add or remove members, and manage admins.",
    adminPermissions: "Admins can add members and remove ordinary members.",
    memberPermissions: "Ordinary members can only add their own contacts.",
    close: "Close",
    refresh: "Refresh",
  },
} as const;

export type Translation = (typeof translations)[Locale];

export function readStoredLocale(): Locale {
  const stored = localStorage.getItem(LOCALE_STORAGE_KEY);
  return stored === "en" || stored === "zh-CN" ? stored : "zh-CN";
}

export function storeLocale(locale: Locale) {
  localStorage.setItem(LOCALE_STORAGE_KEY, locale);
}

export function readStoredTheme(): ThemeMode {
  const stored = localStorage.getItem(THEME_STORAGE_KEY);
  return stored === "light" || stored === "dark" ? stored : "dark";
}

export function storeTheme(theme: ThemeMode) {
  localStorage.setItem(THEME_STORAGE_KEY, theme);
}

export function applyDocumentPreferences(locale: Locale, theme: ThemeMode) {
  document.documentElement.lang = locale;
  document.documentElement.dataset.theme = theme;
  document.documentElement.style.colorScheme = theme;
}
